In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('../DATASETS/Student_Performance.csv')

In [5]:
df.head()

   Study_Hours  Attendance  Assignments  Exam_Score Performance
0           18          30           66           8     Average
1           73          87           14          62        Good
2           98          29          100          47     Average
3            9          98           21          73     Average
4           33          59           67          71        Poor

In [6]:
from sklearn.preprocessing import LabelEncoder

In [8]:
encoder = LabelEncoder()

df['Performance'] = encoder.fit_transform(df['Performance'])

In [9]:
df.head()

   Study_Hours  Attendance  Assignments  Exam_Score  Performance
0           18          30           66           8            0
1           73          87           14          62            2
2           98          29          100          47            0
3            9          98           21          73            0
4           33          59           67          71            3

In [11]:
X = df.drop(columns='Performance')
y= df.iloc[:,-1]

In [12]:
y

0     0
1     2
2     0
3     0
4     3
5     0
6     3
7     3
8     1
9     1
10    0
11    3
12    0
13    3
14    2
15    0
16    1
17    0
18    2
19    3
20    1
21    2
22    1
23    3
24    2
25    1
26    2
27    3
28    3
29    2
30    3
31    2
32    1
33    3
34    0
35    3
36    1
37    0
38    2
39    2
40    1
41    0
42    1
43    1
44    0
45    0
46    2
47    3
48    0
49    2
Name: Performance, dtype: int64

In [13]:
X

    Study_Hours  Attendance  Assignments  Exam_Score
0            18          30           66           8
1            73          87           14          62
2            98          29          100          47
3             9          98           21          73
4            33          59           67          71
5            16          38           51          26
6            64           3           48          65
7            98          54           63          53
8            58          72           94          63
9            61          83            4          46
10           84          13           61          54
11           49          24            6          45
12           27          81           40           1
13           13          93           91          69
14           63          38           79          70
15            4          16           76          80
16           50          96           75          79
17           56          43           51          43
18           78          93           83          59
19           98          92           22          77
20           99          65           22           4
21            1          55           65          30
22           90          65           30          82
23           58          86            2          23
24           35          25           99          71
25           93          39           26          75
26           30          37           70          24
27           76          76           71          12
28           14          64           30          71
29           41          65           52          33
30            4          51           66           5
31            3          76           45          87
32            4           5           74          10
33           84          62           46          11
34           70          32           59           3
35            2          96           35          58
36           49          52           85           2
37           88          54           71          97
38           28          86           78          97
39           55          23           94          36
40           93          47            1          32
41            4          71           50          35
42           68          90           95          15
43           29         100           66          80
44           98          87           17          24
45           57          95           67          45
46           64          48          100          38
47           71          12           72           9
48           30          57           27          22
49           45          85           55          21

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1)

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [23]:
X_train= scaler.fit_transform(X_train)
X_train

array([[-1.37617954e+00, -1.79228848e+00,  7.34698731e-01,
         1.21708257e+00],
       [-5.79085450e-01, -9.74464909e-01,  5.20246129e-01,
        -7.84907038e-01],
       [-6.09742915e-01,  1.47900580e+00,  3.77277727e-01,
         1.21708257e+00],
       [-1.46815193e+00, -2.73473278e-01,  3.41535627e-01,
        -5.70408151e-01],
       [ 1.19904752e+00, -3.12417258e-01,  5.55988229e-01,
         1.82482942e+00],
       [ 3.71295965e-01,  8.16958147e-01, -1.83873250e+00,
         1.58888064e-03],
       [ 1.26036245e+00,  1.15966517e-01, -9.09437889e-01,
         1.28858220e+00],
       [ 2.18008640e-01, -7.40801032e-01, -1.58853780e-01,
        -1.05660563e-01],
       [ 4.63268360e-01, -5.46081135e-01,  1.59250914e+00,
        -2.84409635e-01],
       [-1.06960489e+00,  7.70225372e-02, -9.09437889e-01,
         8.95334243e-01],
       [-1.00828996e+00, -9.35520929e-01, -1.58853780e-01,
        -7.13407409e-01],
       [ 2.48666105e-01,  1.28428590e+00,  4.13019827e-01,
        -3.41609338e-02],
       [-1.37617954e+00,  3.49630394e-01, -1.94595880e-01,
        -3.91659079e-01],
       [ 1.35233484e+00, -5.85025114e-01, -1.94595880e+00,
        -4.98908522e-01],
       [ 1.50562217e+00, -3.12417258e-01,  2.70051426e-01,
         2.51837582e-01],
       [ 1.07641766e+00, -8.65421766e-04, -3.37564282e-01,
        -1.24965463e+00],
       [-1.10026235e+00,  1.20639794e+00,  1.27083024e+00,
         8.23834614e-01],
       [-5.79085450e-01, -1.95585319e-01, -1.01666419e+00,
        -8.56406667e-01],
       [-4.87113055e-01, -1.17697360e-01,  4.13019827e-01,
         8.95334243e-01],
       [ 3.40638500e-03, -1.48073664e+00, -1.76724830e+00,
        -3.41609338e-02],
       [-6.40400380e-01,  9.33790086e-01,  8.06182932e-01,
         1.82482942e+00],
       [-9.46975030e-01, -1.24707277e+00,  3.77277727e-01,
        -1.35690407e+00],
       [ 3.40638500e-03, -3.90305217e-01,  1.05637764e+00,
        -1.57140296e+00],
       [ 1.35233484e+00, -8.96576950e-01, -1.05240629e+00,
         1.03833350e+00],
       [ 1.50562217e+00, -1.28601674e+00,  1.59250914e+00,
         3.73386951e-02],
       [-1.37617954e+00, -2.22067225e+00,  6.63214531e-01,
        -1.28540444e+00],
       [-2.41853335e-01,  1.15966517e-01, -1.23111679e-01,
        -4.63158708e-01],
       [ 4.32610895e-01, -9.35520929e-01,  8.41925033e-01,
         8.59584428e-01],
       [-1.40683700e+00,  5.44350291e-01, -3.73306382e-01,
         1.46733127e+00],
       [-4.25798125e-01, -1.44179266e+00,  1.55676704e+00,
         8.95334243e-01],
       [-1.37617954e+00, -4.29249196e-01,  3.77277727e-01,
        -1.46415351e+00],
       [-1.43749447e+00,  1.32322988e+00, -7.30727387e-01,
         4.30586655e-01],
       [ 2.79323570e-01,  9.33790086e-01, -1.91021670e+00,
        -8.20656853e-01],
       [ 1.53627963e+00,  1.15966517e-01, -1.19537469e+00,
        -1.49990333e+00],
       [-6.71057845e-01,  7.39070188e-01, -5.52016885e-01,
        -1.60715277e+00],
       [ 1.50562217e+00,  9.72734065e-01, -1.37408520e+00,
        -7.84907038e-01],
       [ 2.79323570e-01,  3.88574373e-01,  1.37805654e+00,
         6.09335727e-01],
       [ 1.07641766e+00, -1.90912042e+00,  1.98567225e-01,
         2.87587397e-01],
       [ 8.31157940e-01,  5.44350291e-01,  5.55988229e-01,
        -1.21390481e+00],
       [ 3.40638500e-02,  1.32322988e+00,  6.98956631e-01,
         1.18133276e+00],
       [-1.22289221e+00,  1.40111784e+00, -1.23111679e+00,
         9.66833872e-01],
       [ 8.92472870e-01,  1.20639794e+00,  9.84893435e-01,
         4.66336469e-01],
       [-1.19223475e-01,  8.94846106e-01, -1.58853780e-02,
        -8.92156482e-01],
       [ 5.85898220e-01,  1.08956600e+00,  1.41379864e+00,
        -1.10665537e+00],
       [ 1.50562217e+00,  1.16745396e+00, -1.19537469e+00,
         1.10983313e+00]])

In [25]:
X_test=scaler.transform(X_test)
X_test

array([[70., 32., 59.,  3.],
       [55., 23., 94., 36.],
       [73., 87., 14., 62.],
       [64.,  3., 48., 65.],
       [71., 12., 72.,  9.]])

In [34]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression()

In [35]:
y_pred=clf.predict(X_test)

In [36]:
y_test

34    0
39    2
1     2
6     3
47    3
Name: Performance, dtype: int64

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy_score(y_test,y_pred)

0.2

In [40]:
import pickle

In [42]:
pickle.dump(clf,open('Student.pkl','wb'))